import re

file_path = 'server/agents/codingAgent.ts'

with open(file_path, 'r') as f:
    content = f.read()

# Pattern to find the TODO block
pattern_str = r"(\s+// TODO: In production:.*?//   await createPRForSandbox\(sandbox\);\n  // })"

replacement_str = """
  // SCPA Lifecycle Implementation
  try {
    console.log('🚀 [SCPA] Starting automated fix lifecycle');

    // 1. Create sandbox
    const sandboxName = `scpa-fix-${Date.now()}`;
    const sandbox = await createSandbox({
      name: sandboxName,
      description: `SCPA Fix for ${failureContext.agentName}: ${failureContext.error}`,
      createdBy: 'milla',
    });

    // 2. Add feature metadata (required for testFeature)
    const feature = await addFeatureToSandbox(sandbox.id, {
        name: `Fix for ${failureContext.error}`,
        description: mockFix.description,
        files: mockFix.files
    });

    if (feature) {
        // 3. Apply patch to sandbox branch
        const patchApplied = await applyPatchToSandbox(sandbox.id, mockFix);

        if (patchApplied) {
             // 4. Run tests
             console.log('🧪 [SCPA] Running tests in sandbox...');
             const unitTest = await testFeature(sandbox.id, feature.id, 'unit');
             const integrationTest = await testFeature(sandbox.id, feature.id, 'integration');

             if (unitTest.passed && integrationTest.passed) {
                 console.log('✅ [SCPA] Tests passed, creating PR...');
                 // 5. Create PR
                 const pr = await createPRForSandbox({
                     sandboxId: sandbox.id,
                     title: `[SCPA] Fix for ${failureContext.agentName} failure`,
                     description: `Automated fix generated by SCPA for error: ${failureContext.error}\\n\\n${mockFix.description}`,
                     branch: sandbox.branchName,
                     files: mockFix.files,
                     skipCommit: true // Important: we already committed
                 });
                 console.log(`🎉 [SCPA] PR Created: ${pr.id}`);
             } else {
                 console.warn('⚠️ [SCPA] Tests failed, manual intervention required');
             }
        } else {
            console.error('❌ [SCPA] Failed to apply patch');
        }
    }
  } catch (err) {
      console.error(`❌ [SCPA] Lifecycle error: ${err}`);
  }"""

# Use re.sub with DOTALL
content = re.sub(pattern_str, replacement_str, content, count=1, flags=re.DOTALL)

with open(file_path, 'w') as f:
    f.write(content)

print("Successfully updated generateFix in server/agents/codingAgent.ts")
