name: Feature request
description: Propose an enhancement or new capability
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem does this address?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior or API you'd like.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
