name: 'Mint Identity Token'
description: 'Mints a GitHub App token'
inputs:
  app_id:
    description: 'The GitHub App ID'
    required: false
  private_key:
    description: 'The GitHub App Private Key'
    required: false
outputs:
  token:
    description: 'The minted GitHub App token'
    value: ${{ steps.mint_identity_token.outputs.token }}
runs:
  using: 'composite'
  steps:
    - name: 'Mint identity token'
      id: 'mint_identity_token'
      if: |-
        ${{ inputs.app_id }}
      uses: 'actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b' # ratchet:actions/create-github-app-token@v2
      with:
        app-id: '${{ inputs.app_id }}'
        private-key: '${{ inputs.private_key }}'
        permission-contents: 'read'
        permission-issues: 'write'
        permission-pull-requests: 'write'
